USE [master]
GO

/****** Object:  Database [Schedule_app]    Script Date: 11/26/2022 10:10:05 PM ******/
CREATE DATABASE [Schedule_app]
 
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Schedule_app].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Schedule_app] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Schedule_app] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Schedule_app] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Schedule_app] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Schedule_app] SET ARITHABORT OFF 
GO

ALTER DATABASE [Schedule_app] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Schedule_app] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Schedule_app] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Schedule_app] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Schedule_app] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Schedule_app] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Schedule_app] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Schedule_app] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Schedule_app] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Schedule_app] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Schedule_app] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Schedule_app] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Schedule_app] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Schedule_app] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Schedule_app] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Schedule_app] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Schedule_app] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Schedule_app] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Schedule_app] SET  MULTI_USER 
GO

ALTER DATABASE [Schedule_app] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Schedule_app] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Schedule_app] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Schedule_app] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Schedule_app] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Schedule_app] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Schedule_app] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Schedule_app] SET  READ_WRITE 
GO

USE [Schedule_app]
GO

/****** Object:  Table [dbo].[Accounts]    Script Date: 11/26/2022 10:09:27 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Accounts](
	[Username] [nvarchar](50) NOT NULL,
	[Password] [nvarchar](50) NULL,
 CONSTRAINT [PK_Accounts] PRIMARY KEY CLUSTERED 
(
	[Username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [Schedule_app]
GO

/****** Object:  Table [dbo].[Reminder]    Script Date: 11/26/2022 10:09:52 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

USE [Schedule_app]
GO

/****** Object:  Table [dbo].[Notes]    Script Date: 11/26/2022 10:09:37 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Notes](
	[Title] [nvarchar](250) NOT NULL,
	[Content] [text] NULL,
	[ID] [bigint] NOT NULL IDENTITY,
	[Reminder] [nchar](10) NULL,
	[accounts] [nvarchar](50) NULL,
 CONSTRAINT [PK_Notes] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[Notes]  WITH CHECK ADD FOREIGN KEY([accounts])
REFERENCES [dbo].[Accounts] ([Username])
GO



CREATE TABLE [dbo].[Reminder](
	[Title] [nchar](250) NOT NULL,
	[Content] [text] NULL,
	[creation] [datetime] NULL,
	[runOn] [datetime] NULL,
	[accounts] [nvarchar](50) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[Reminder]  WITH CHECK ADD FOREIGN KEY([accounts])
REFERENCES [dbo].[Accounts] ([Username])
GO


